### ISSUE TITLE
uiSref only work if used on anchor tag using keyboard

### ISSUE THREAD

**Issue by croeber** [ui-router/angular#167] opened 2017-11-06 19:40 UTC
This works

```
<li *ngFor="let person of people">
    <a uiSref=".person" [uiParams]="{ personId: person.id }">
      {{person.name}}
    </a>
 </li>
```

This does not when using the keyboards enter key to navigate to state

```
<div *ngFor="let person of people">
    <div uiSref=".person" [uiParams]="{ personId: person.id }">
      {{person.name}}
    </div>
 </div>
```

**Comment by kubek80** [comment] 2017-11-06 23:59
From accessibility point of view that's expected behaviour.

You can add role="button", maybe tabindex and aria-label to your div but only if you really have to use it (<a> and <button> are preferred).

**Comment by christopherthielen** [comment] 2017-11-15 19:16
Closing because this is working as expected.  Thanks @kubek80 for the details

**Closed by christopherthielen** 2017-11-15 19:16 UTC

**Comment by croeber** [comment] 2018-01-04 21:26
Looks like your team enable key navigation anyways. Thanks. Makes since to me.
