### ISSUE TITLE
webpack: Failed to compile with 4.2.0

### ISSUE THREAD

**Issue by kolkov** [ui-router/angular#125] opened 2017-06-09 19:12 UTC
Hi! After update to v.4.2.0 I got an error:
![image](https://user-images.githubusercontent.com/3740898/26990766-7d6ef0b4-4d60-11e7-8213-4aebea1dfab3.png)

**Comment by kolkov** [comment] 2017-06-10 18:54
I tryed to use this solution, but got an error:
![image](https://user-images.githubusercontent.com/3740898/27005430-3dbe31d8-4e27-11e7-98e2-8e7d95df24a2.png)

**Comment by kolkov** [comment] 2017-06-10 20:01
I fixed this!
I removed `"@uirouter/core": "^5.0.0"` from `package.json`.
Then I removed `package-lock.json` file
Then I deleted `node_modules` folder
And then I ran `npn install `
Profit!

**Comment by aitboudad** [comment] 2017-06-12 09:35
Not sure there is something we can do here, it's an npm issue I think.

**Comment by mkoczorowski** [comment] 2017-06-12 22:06
I would close this one. All works fine after removing npm_modules and doing npm cache clean, npm install

**Comment by kolkov** [comment] 2017-06-13 12:46
Maybe someone can ask a technically correct question in the npm tracker? Thanks!

**Comment by christopherthielen** [comment] 2017-06-17 18:43
So the root cause was duplicate copies of `@uirouter/core`.

- the app's package.json requested `"@uirouter/core": "^5.0.0"` and got `5.0.3`
- `@uirouter/angular` requested `"@uirouter/core": "5.0.0"` and got exactly `5.0.0` inside its node_modules

Intuitively, I would expect a single version which satisfies both semver ranges (`5.0.0`)  installed at the root level.

Interesting to note that yarn handles this scenario, but npm does not.

Related: https://github.com/ui-router/sample-app-angular/issues/4#issuecomment-304755883

**Closed by christopherthielen** 2017-06-17 18:43 UTC

**Comment by bopm** [comment] 2017-10-03 12:55
@christopherthielen it's back again on fresh installs. `@uirouter/core` not mentioned in `package.json` gets installed to `5.0.9`. After that `No Provider for StateService` error appear. Adding `"@uirouter/core": "5.0.5"` to `package.json` fixes things.

**Comment by christopherthielen** [comment] 2017-10-04 18:12
@bopm you don't have an explicit dependency on `@uirouter/core` but it's pulling in 5.0.9?

Can you find the dependency that is adding it?  `yarn ls` or `npm ls` and search for `@uirouter/core`

**Comment by bopm** [comment] 2017-10-06 15:38
@christopherthielen 
```
├─ @uirouter/angular@1.0.0-beta.7-SNAPSHOT.20170812
│  ├─ @uirouter/core@^5.0.5
│  ├─ @uirouter/rx@=0.4.1
│  └─ tslib@^1.7.1
├─ @uirouter/core@5.0.10
├─ @uirouter/rx@0.4.1
│  ├─ rollup-plugin-commonjs@^8.0.2
│  ├─ rollup-plugin-node-resolve@^3.0.0
│  ├─ rollup-plugin-progress@^0.2.1
│  ├─ rollup-plugin-sourcemaps@^0.4.2
│  ├─ rollup-plugin-uglify@^1.0.2
│  ├─ rollup-plugin-visualizer@^0.2.1
│  └─ rollup@^0.41.6
```
So it's just updated on `5.0.10` if not locked.

**Comment by christopherthielen** [comment] 2017-10-06 19:57
@bopm will you link to a gist of your entire package.json which shows the error? The lines you pasted imply that you have a top level dependency on `core`

**Comment by bopm** [comment] 2017-10-07 11:18
[here](https://gist.github.com/bopm/8a4350e3f333e9c48792c660824327e0) it is. I use yarn `1.1.0` for installing packages.

**Comment by christopherthielen** [comment] 2017-10-10 16:25
@bopm 

Ah, I see now!  `^1.0.0-beta.7` is installing `1.0.0-beta.7-SNAPSHOT.20170812`

Update to 1.0.0-beta.8 and this should be resolved.
